version: '3'

services:
  web:
    build: ./
    volumes:
      - .:/app
      - /home/kakakaya:/host
    ports:
      - "12019:80"
    environment:
      - FLASK_APP=web.py
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
